# Generated by Django 2.1.7 on 2019-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('contact_self', models.CharField(max_length=12)),
                ('contact_father', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cc_of', models.CharField(blank=True, max_length=30)),
                ('cc_of_year', models.CharField(blank=True, max_length=30)),
                ('class1', models.CharField(blank=True, max_length=30)),
                ('class2', models.CharField(blank=True, max_length=30)),
                ('sub2', models.CharField(blank=True, max_length=30)),
                ('class3', models.CharField(blank=True, max_length=30)),
                ('sub3', models.CharField(blank=True, max_length=30)),
                ('class4', models.CharField(blank=True, max_length=30)),
                ('sub4', models.CharField(blank=True, max_length=30)),
                ('class5', models.CharField(blank=True, max_length=30)),
                ('sub1', models.CharField(blank=True, max_length=30)),
                ('class6', models.CharField(blank=True, max_length=30)),
                ('sub6', models.CharField(blank=True, max_length=30)),
                ('class7', models.CharField(blank=True, max_length=30)),
                ('sub7', models.CharField(blank=True, max_length=30)),
                ('class8', models.CharField(blank=True, max_length=30)),
                ('sub8', models.CharField(blank=True, max_length=30)),
                ('class9', models.CharField(blank=True, max_length=30)),
                ('sub9', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
