# Generated by Django 2.1.7 on 2019-04-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('roll_no', models.CharField(max_length=20)),
                ('rtu_roll_no', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('dob', models.DateTimeField()),
                ('contact_self', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=12)),
                ('contact_father', models.CharField(max_length=12)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='class_info.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('teacher_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('teacher_id', models.CharField(max_length=20)),
                ('dob', models.DateTimeField(max_length=200)),
                ('joining_year', models.DateTimeField()),
                ('address', models.TextField(max_length=200)),
                ('is_hod', models.BooleanField(default=False)),
                ('is_cc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class_info.Classes')),
            ],
        ),
    ]
