# Generated by Django 2.1.7 on 2019-04-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190414_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.TeacherProfile'),
        ),
    ]
