# Generated by Django 2.1.7 on 2019-04-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190418_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_cc',
            field=models.BooleanField(default=False),
        ),
    ]
