# Generated by Django 2.1.7 on 2019-04-14 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_info', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slot1', models.CharField(max_length=20)),
                ('slot2', models.CharField(max_length=20)),
                ('slot3', models.CharField(max_length=20)),
                ('slot4', models.CharField(max_length=20)),
                ('slot5', models.CharField(max_length=20)),
                ('slot6', models.CharField(max_length=20)),
                ('slot7', models.CharField(max_length=20)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_info.Classes')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='total_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.IntegerField()),
                ('classes_attended', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.StudentProfile')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Subjects')),
            ],
        ),
    ]
