# Generated by Django 2.1.7 on 2019-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('studentId', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('classId', models.CharField(max_length=3)),
                ('sub1', models.CharField(blank=True, max_length=40)),
                ('sub2', models.CharField(blank=True, max_length=40)),
                ('sub3', models.CharField(blank=True, max_length=40)),
                ('sub4', models.CharField(blank=True, max_length=40)),
                ('sub5', models.CharField(blank=True, max_length=40)),
                ('sub6', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='total_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('sub2', models.IntegerField()),
                ('sub3', models.IntegerField()),
                ('sub4', models.IntegerField()),
                ('sub5', models.IntegerField()),
                ('sub6', models.IntegerField()),
            ],
        ),
    ]
