# Generated by Django 2.1.7 on 2019-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='total_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('sub2', models.IntegerField(max_length=4)),
                ('sub3', models.IntegerField(max_length=4)),
                ('sub4', models.IntegerField(max_length=4)),
                ('sub5', models.IntegerField(max_length=4)),
                ('sub6', models.IntegerField(max_length=4)),
            ],
        ),
    ]
