# Generated by Django 2.1.7 on 2019-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('studentId', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('classId', models.CharField(max_length=3)),
                ('sub1', models.CharField(blank=True, max_length=40)),
                ('sub2', models.CharField(blank=True, max_length=40)),
                ('sub3', models.CharField(blank=True, max_length=40)),
                ('sub4', models.CharField(blank=True, max_length=40)),
                ('sub5', models.CharField(blank=True, max_length=40)),
                ('sub6', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
