# Generated by Django 2.1.7 on 2019-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.IntegerField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('sub1', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('classroom', models.CharField(max_length=20)),
            ],
        ),
    ]
