# Generated by Django 2.1.7 on 2019-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('contact_self', models.CharField(max_length=12)),
                ('contact_father', models.CharField(max_length=12)),
            ],
        ),
    ]
